### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by zeroeightysix**
General consensus was LGPL3. If you do not agree, please leave a comment with (constructive) criticism for why we should opt for another license.

### CODE REVIEW

**Review by 5HT2 — CHANGES_REQUESTED** [review]
Should be in markdown formatting 😄

**Review by 5HT2 — APPROVED** [review]

**Comment by x4e** [comment]
Is there a need for a license?

**Comment by zeroeightysix** [comment]
Yes, because open source software with no license isn't open source.

A license allows us to give permission to people using the library in advance, without them needing to consult us on whether or not they're supposed to use the library in their specific setting.

**Comment by jackflip** [comment]
How about Coffee license? If you like it buy us a coffee? That way people can use it as they wish and if they like it, they donate.

**Comment by EmotionalLove** [comment]
> How about Coffee license? If you like it buy us a coffee? That way people can use it as they wish and if they like it, they donate.

I want Starbucks >.>

**Comment by jackflip** [comment]
> > How about Coffee license? If you like it buy us a coffee? That way people can use it as they wish and if they like it, they donate.
> 
> I want Starbucks >.>

One iced caramel macchiato with light ice please!

**Comment by zeroeightysix** [comment]
> How about Coffee license? If you like it buy us a coffee? That way people can use it as they wish and if they like it, they donate.

Is this a real license? Could you provide a link?

**Review by IronException — APPROVED** [review]

**Comment by x4e** [comment]
Good point @zeroeightysix

**Review by x4e — APPROVED** [review]

**Comment by x4e** [comment]
All the contributors have approved so lets merge

**Pull request merged**
