### PR TITLE
Separate libraries

### PR DESCRIPTION
**Pull request by zeroeightysix**
This pull requests implements a rewrite of `PersonLoader`, separates the core library (everything without a dependency on minecraft) and creates a new library, `UniversalFriends-minecraft`.

### CODE REVIEW

**Review by IronException — APPROVED** [review]
Why not all in Meta? I get that value should be treaten differently but since we want to do things as abstract as possible be could also offer the option to have no value?

**Comment by zeroeightysix** [comment]
> Why not all in Meta?

What do you mean by *all*? Include the name, id, and value in the metadata as well?

> I get that value should be treated differently but since we want to do things as abstract as possible be could also offer the option to have no value?

We could, but that's going to make things too complex and a hassle to deal with for other developers. Java's primitive `double` is easy to manipulate (e.g. comparisons, additions/subtractions etc) but can not be equal to `null`.
If we were to make values optional, we'd have to use something like a `Double` (the boxed equivalent of `double`) which would make basic operations a pain to deal with and read.

Consider the following (primitive `double):
```java
return person.getValue() > otherPerson.getValue();
```

vs (using  `Double`):
```java
if (person.getValue() != null && otherPerson.getValue() != null) {
    return person.getValue().doubleValue() > otherPerson.getValue().doubleValue();
}
```

**Comment by zeroeightysix** [comment]
Sure, we could abstract `IPerson` even more and have a `IPerson`s only have metadata, id and name, and have a separate interface for value, but that'd require a rewrite of quite a large portion of the library. (And would also require changing the standard quite a bit!)

**Comment by IronException** [comment]
Agreed: everyone has a name and UUID so that should be saved for sure. Also saving the things we have set as a standard makes sense to have there as concrete values. The other values need to be set then tho.

I worry more about the fact that we will stop ourselves to test whether someone has a value with that.
In an earlier comment, we agreed that having no value should be different from having the neutral value (although both would be treated the same on the friendliness scale), With forcing the value variable to exist we can't do that anymore. When something is only saved in meta eg.

**Comment by zeroeightysix** [comment]
Issues solved in a private conversation, merging.

**Pull request merged**
